# Generated by Django 4.2.5 on 2023-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, max_length=325, null=True, verbose_name='short summary')),
                ('phone', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('adress', models.TextField(blank=True, max_length=325, null=True)),
                ('work', models.TextField(blank=True, max_length=325, null=True, verbose_name='working date & time')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Informations',
                'ordering': ['-id'],
            },
        ),
    ]
