# Generated by Django 4.2.5 on 2023-10-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInformation',
            new_name='ContactInformationModel',
        ),
        migrations.RenameField(
            model_name='contactinformationmodel',
            old_name='adress',
            new_name='address',
        ),
    ]
