# Generated by Django 4.2.5 on 2023-10-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_productcategorymodel_productsubcategorymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagesmodel',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productimagesmodel',
            name='image_title',
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='details',
            field=models.TextField(blank=True, max_length=325, null=True, verbose_name='Short Summary'),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='work',
            field=models.TextField(blank=True, max_length=325, null=True, verbose_name='Working Date & Time'),
        ),
        migrations.AlterField(
            model_name='footerinformationmodel',
            name='details',
            field=models.TextField(max_length=325, null=True, verbose_name='Short Summary'),
        ),
        migrations.AlterField(
            model_name='productimagesmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_main.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_main.productcategorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cover_image',
            field=models.ImageField(help_text='Size Direction: W:800PX & H:975PX', null=True, upload_to='product-cover-image/%Y/%d/%b'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='details',
            field=models.TextField(blank=True, max_length=325, null=True, verbose_name='Product Details'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='info',
            field=models.TextField(blank=True, max_length=325, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_main.productsubcategorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=122, null=True, verbose_name='Product Title'),
        ),
    ]
