# Generated by Django 4.2.5 on 2023-10-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_productimagesmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategorymodel',
            old_name='sub_category_name',
            new_name='subcategory_name',
        ),
    ]
