# Generated by Django 4.2.5 on 2023-10-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_rename_sub_category_name_productsubcategorymodel_subcategory_name'),
        ('app_main', '0006_reviewmodel_alter_headerslidermodel_bg_img_and_more'),
    ]

    operations = [
    ]
