# Generated by Django 4.2.5 on 2023-10-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_merge_20231007_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(default='Brand Gallery Object', max_length=125, null=True, verbose_name='object name')),
                ('left_img', models.ImageField(help_text='image size: w-1000px x h-1000', null=True, upload_to='brand-gallery', verbose_name='left site image')),
                ('top_img', models.ImageField(help_text='image size: w-1000px x h-480', null=True, upload_to='brand-gallery', verbose_name='top site image')),
                ('bottom_img', models.ImageField(help_text='image size: w-1000px x h-480', null=True, upload_to='brand-gallery', verbose_name='bottom site image')),
            ],
            options={
                'verbose_name': 'Brand Gallery',
                'verbose_name_plural': 'Brand Gallery',
            },
        ),
        migrations.AlterField(
            model_name='headerslidermodel',
            name='bg_img',
            field=models.ImageField(help_text='image size: w-1920px x h-1100', null=True, upload_to='headersliderbg', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='productsubcategorymodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app_main.productcategorymodel'),
        ),
    ]
