# Generated by Django 4.2.5 on 2023-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_brandgallerymodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=125, null=True, verbose_name='partner company name')),
                ('logo', models.ImageField(help_text='image size: w-230px x h-140', null=True, upload_to='partner-company-logos')),
            ],
            options={
                'verbose_name': 'Partner Company Logo',
                'verbose_name_plural': 'Partner Company Logos',
            },
        ),
    ]
