# Generated by Django 4.2.5 on 2023-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_partnercompanymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAboutInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(max_length=555, null=True)),
            ],
            options={
                'verbose_name': 'Short About Information',
                'verbose_name_plural': 'Short About Informations',
            },
        ),
    ]
