# Generated by Django 4.2.5 on 2023-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_shortaboutinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gemotex Intro Video', max_length=200, null=True)),
                ('link', models.URLField(null=True, verbose_name='video link')),
                ('thumbnail', models.ImageField(help_text='image size: w-1920px x h-700', null=True, upload_to='intro-thumbnail', verbose_name='video thumbnail')),
            ],
            options={
                'verbose_name': 'Introduction Video',
                'verbose_name_plural': 'Introduction Video',
            },
        ),
    ]
