# Generated by Django 4.2.5 on 2023-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_introvideomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('sub_title', models.CharField(max_length=50, null=True)),
                ('btn_text', models.CharField(max_length=100, null=True)),
                ('btn_link', models.URLField(null=True, verbose_name='video link')),
                ('details', models.TextField(max_length=525, null=True, verbose_name='card details')),
                ('card_img', models.ImageField(help_text='image size: w-800px x h-800px', null=True, upload_to='about-card-images', verbose_name='card image')),
            ],
            options={
                'verbose_name': 'About Card',
                'verbose_name_plural': 'About Cards',
            },
        ),
        migrations.AlterField(
            model_name='introvideomodel',
            name='thumbnail',
            field=models.ImageField(help_text='image size: w-1920px x h-700px', null=True, upload_to='intro-thumbnail', verbose_name='video thumbnail'),
        ),
    ]
