# Generated by Django 4.2.5 on 2023-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_aboutcardmodel_alter_introvideomodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gemotex About Video', max_length=200, null=True)),
                ('link', models.URLField(null=True, verbose_name='video link')),
                ('thumbnail', models.ImageField(help_text='image size: w-1920px x h-700px', null=True, upload_to='about-thumbnail', verbose_name='video thumbnail')),
            ],
            options={
                'verbose_name': 'About Video',
                'verbose_name_plural': 'About Video',
            },
        ),
    ]
