# Generated by Django 4.2.5 on 2023-10-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_aboutvideomodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsubcategorymodel',
            unique_together={('category', 'subcategory_name')},
        ),
        migrations.CreateModel(
            name='FeaturedProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='app_main.productmodel')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
            },
        ),
    ]
