# Generated by Django 4.2.5 on 2023-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_alter_partnercompanymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='term & condition title')),
                ('dsc', models.TextField(max_length=999, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Terms & ConditionsModel',
                'verbose_name_plural': 'Terms & ConditionsModel',
            },
        ),
    ]
