# Generated by Django 4.2.6 on 2023-10-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_termsandconditionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsandconditionsmodel',
            options={'verbose_name': 'Terms & Conditions', 'verbose_name_plural': 'Terms & Conditions'},
        ),
    ]
