# Generated by Django 4.2.5 on 2023-10-21 18:47

import app_main.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_alter_termsandconditionsmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinformationmodel',
            name='instagram_link',
        ),
        migrations.AddField(
            model_name='footerinformationmodel',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin Link'),
        ),
        migrations.AlterField(
            model_name='aboutcardmodel',
            name='card_img',
            field=models.ImageField(help_text='image size: w-800px x h-800px', null=True, upload_to='about-card-images', validators=[app_main.models.validate_file_size], verbose_name='card image'),
        ),
        migrations.AlterField(
            model_name='aboutvideomodel',
            name='thumbnail',
            field=models.ImageField(help_text='image size: w-1920px x h-700px', null=True, upload_to='about-thumbnail', validators=[app_main.models.validate_file_size], verbose_name='video thumbnail'),
        ),
        migrations.AlterField(
            model_name='brandgallerymodel',
            name='bottom_img',
            field=models.ImageField(help_text='image size: w-1000px x h-480', null=True, upload_to='brand-gallery', validators=[app_main.models.validate_file_size], verbose_name='bottom site image'),
        ),
        migrations.AlterField(
            model_name='brandgallerymodel',
            name='left_img',
            field=models.ImageField(help_text='image size: w-1000px x h-1000', null=True, upload_to='brand-gallery', validators=[app_main.models.validate_file_size], verbose_name='left site image'),
        ),
        migrations.AlterField(
            model_name='brandgallerymodel',
            name='top_img',
            field=models.ImageField(help_text='image size: w-1000px x h-480', null=True, upload_to='brand-gallery', validators=[app_main.models.validate_file_size], verbose_name='top site image'),
        ),
        migrations.AlterField(
            model_name='headerslidermodel',
            name='bg_img',
            field=models.ImageField(help_text='image size: w-1920px x h-1100', null=True, upload_to='headersliderbg', validators=[app_main.models.validate_file_size], verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='introvideomodel',
            name='thumbnail',
            field=models.ImageField(help_text='image size: w-1920px x h-700px', null=True, upload_to='intro-thumbnail', validators=[app_main.models.validate_file_size], verbose_name='video thumbnail'),
        ),
        migrations.AlterField(
            model_name='partnercompanymodel',
            name='logo',
            field=models.ImageField(help_text='image size: w-230px x h-140', null=True, upload_to='partner-company-logos', validators=[app_main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productimagesmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='products-images/%Y/%d/%b', validators=[app_main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='cover_image',
            field=models.ImageField(help_text='Size Direction: W:800PX & H:975PX', null=True, upload_to='product-cover-image/%Y/%d/%b', validators=[app_main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='details',
            field=models.TextField(blank=True, max_length=555, null=True, verbose_name='Product Details'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=99999, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='client-review-profiles', validators=[app_main.models.validate_file_size], verbose_name='person image'),
        ),
    ]
